version: "3.3"
services:
    api:
        build: .
        ports:
            - "5000:5000"
            - "8080:8080"
    prometheus:
        image: prom/prometheus
        volumes:
            - ./dev/prometheus/:/etc/prometheus/
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana:7.2.0
        volumes:
            - grafana_data:/var/lib/grafana
        ports:
            - 3000:3000


volumes:
    prometheus_data: {}
    grafana_data: {}
